---
title: "p8105_hw2_sc5352.Rmd"
author: "Chrissy Chen"
date: "2023-09-30"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Problem 1  
```{r}
library(tidyverse)
```

#### clean the data in pols-month.csv
```{r}
pols_month = 
  read_csv("data/pols-month.csv") |>
  separate(mon, into = c("year", "month", "day"), sep = "-") |>
  mutate(
    year = as.integer(year), 
    month = as.integer(month), 
    day = as.integer(day),
    month = month.abb[month],
    president = ifelse(prez_gop == 1, "gop", "dem")
    ) |>
  select(-prez_gop, -prez_dem, -day)
  #mutate(month = month.name[month])
  #cols(year = col_integer(), month = col_integer(), day = col_integer()) 

pols_month
```

#### clean the data in snp.csv 
```{r}
snp = 
  read_csv("data/snp.csv") |>
  separate(date, c("month", "day", "year"), "/") |>
  mutate(
    month = as.integer(month),
    month = month.abb[month],
    year = as.integer(year),
    day = as.integer(day)
  ) |>
  select(year, month, everything())
```

#### tidy the unemployment data
```{r}
unemployment = 
  read_csv("data/unemployment.csv")
```

### Problem 2

```{r}
library(dbplyr)
library(readxl)
library(tidyverse)
```

```{r}
Mr_Trash_Wheel = 
  read_excel("Trash Wheel.xlsx", sheet = "Mr. Trash Wheel") |>
  janitor::clean_names() |> 
  select(-x15,-x16) |> 
  mutate(
    homes_powered = (weight_tons*500)/30,
    type = "Mr_Trash_Wheel"
  )
Prof_Trash_Wheel = 
  read_excel("Trash Wheel.xlsx", sheet = "Professor Trash Wheel") |>
  janitor::clean_names() |>
  mutate(
    homes_powered = (weight_tons*500)/30,
    type = "Prof_Trash_Wheel",
    year = as.character(year), 
    month = as.character(month)
  )
Gwynnda = 
  read_excel("Trash Wheel.xlsx", sheet = "Gwynnda Trash Wheel") |>
  janitor::clean_names() |>
  mutate(
    homes_powered = (weight_tons*500)/30,
    type = "Gwynnda",
    year = as.character(year), 
    month = as.character(month)
  )
combine_data = bind_rows(Mr_Trash_Wheel,Prof_Trash_Wheel)
all_data = bind_rows(combine_data, Gwynnda)
```

### Problem 3
```{r}
baseline = 
  read_csv("data_mci/MCI_baseline.csv", skip = 1) |>
  janitor::clean_names() |>
  mutate(
    sex = ifelse(sex == 1, "male", "female"),
    apoe4 = ifelse(apoe4 == 1, "carrier", "noncarrier")) |>
  filter(age_at_onset != '.')

amyloid = 
  read_csv("data_mci/mci_amyloid.csv", skip = 1) |>
  janitor::clean_names() |>
  rename(id = study_id)

total_data = inner_join(baseline, amyloid, by="id")
```

